- Modules/xSharePoint/DSCResources/MSFT_xSPDistributedCacheService/MSFT_xSPDistributedCacheService.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPDistributedCacheService/MSFT_xSPDistributedCacheService.schema.mof
- README.md
Adding a change to xSPDistributedCacheService to add an optional property "ServerProvisionOrder". What this does is makes sure that the cache is provisioned fully on previous servers before running locally. For example:
xSPDistributedCacheService EnableDistributedCache
{
Name                 = "AppFabricCachingService"
Ensure               = "Present"
CacheSizeInMB        = 4096
ServiceAccount       = $ServicePoolManagedAccount.UserName
PsDscRunAsCredential = $SPSetupAccount
CreateFirewallRules  = $true
ServerProvisionOrder = @("Server1", "Server2", "Server3")
DependsOn            = "[WaitForAll]WaitForServiceAppAccount"
}
In this case server1 will run right away, server 2 will wait until it sees the cache running on server 1, and server 3 will wait to see it running on both servers 1 and …
> Improved support for multiple servers with distributed cache

- Modules/xSharePoint/DSCResources/MSFT_xSPDistributedCacheService/MSFT_xSPDistributedCacheService.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPSearchTopology/MSFT_xSPSearchTopology.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPServiceInstance/MSFT_xSPServiceInstance.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPUserProfileSyncService/MSFT_xSPUserProfileSyncService.psm1
We initially saw this bug about 10 months ago but couldn't reproduce so left it alone. It's finally reared its head again and I've been able to squash it. The scenario is that in some SharePoint installations you will see SPServer objects referred to using a FQDN (like "server.domain.name") instead of just the server name. This breaks xSPServiceInstance, xSPUserProfileSync, xSPSearchTopology and xSPDistributedCacheService as they all refer to these server objects in some form, so this PR covers a fix for each that sees us try to load a service instance from the computer name alone first, and if that returns null we re-run the check using the FQDN. 
Code review time @caadam @camiloborges @ykuijs @anlynes
> Bug fix for SPServer objects that use FQDNs

- Modules/xSharePoint/DSCResources/MSFT_xSPFarmAdministrators/MSFT_xSPFarmAdministrators.psm1
- README.md
@ykuijs Can I get you to review this one dude since it was your resource to begin with? The issue is that I was seeing SharePoint return "domain\user" where as my config had "Domain\User" (casing was the only difference) and it would fail a test, despite the user being in the group already. Just switched the Contains() method out for the PowerShell contains operator which isn't case sensitive.
> Fixed case sensitive check of farm admins resource

- Modules/xSharePoint/DSCResources/MSFT_xSPManagedMetadataServiceApp/MSFT_xSPManagedMetaDataServiceApp.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPManagedMetadataServiceApp/MSFT_xSPManagedMetaDataServiceApp.schema.mof
- README.md
@ykuijs @caadam @camiloborges @anlynes - Code review. Quick one here, just added an option to provision MMS with a content type hub URL. I'll add a work item tagged as technical debt to track the fact that we don't monitor this URL and update it once the MMS is provisioned (found an easy way to set it, but no easy way to retrieve the current value) so we can revisit this later, but I wanted to get the basic property in so we didn't need to make a schema change later to add the property.
> Added basic CT Hub URL parameter

- Modules/xSharePoint/DSCResources/MSFT_xSPAlternateUrl/MSFT_xSPAlternateUrl.psm1
- README.md
- Tests/xSharePoint/xSharePoint.xSPAlternateUrl.Tests.ps1
@caadam @camiloborges @anlynes @ykuijs Code review time - This is a quick one to account for the AAMs being changed in the default zone.
> Fixed bug with default URLs being changed in xSPAlternateUrl

- README.md
Documentation update:
Update README.md due to incorrect link to changelog file (lowercase instead of uppercase filename)
Thanks for submitting a Pull Request to this project.
Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).
To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
Your contribution to this project is greatly appreciated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/301)
> Update README.md due to incorrect link to changelog file (lowercase instead of uppercase filename)

- CHANGELOG.md
- Modules/SharePointDSC/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1
Quick one to fix a bug I found in SPTimerJobState - looks like the object coming back from schedule is a custom object, not a string (it's ToString() method hides that though so it looks like a string until you interrogate it). A quick ToString() on it in the get method stops the tests from throwing a false result when it is actually set correctly.
@ykuijs You wanna code review this one seeing as that module was yours to begin with? Thanks dude
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/303)
> Fixed bug with schedule type not being tested as a string

- CHANGELOG.md
- Modules/SharePointDSC/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDSC/Modules/SharePointDSC.Util/SharePointDSC.Util.psm1
- Modules/SharePointDSC/SharePointDSC.psd1
- Tests/SharePointDSC/SharePointDSC.SPServiceAppSecurity.Tests.ps1
This is a fix to a minor issue where the wrong claim type is used when applying permissions to AD groups instead of users for service app sharing and admin permissions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/307)
> Fix to group permissions in SPServiceAppSecurity

- .vscode/ScriptAnalyzerSettings.psd1
- CHANGELOG.md
- Modules/SharePointDSC/Examples/Single Server/SharePoint.ps1
- Modules/SharePointDSC/Examples/Small Farm/SharePoint.ps1
- Modules/SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerBinding/MSFT_SPOfficeOnlineServerBinding.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPOfficeOnlineServerBinding/MSFT_SPOfficeOnlineServerBinding.schema.mof
- Tests/SharePointDsc/SharePointDsc.SPOfficeOnlineServerBinding.Tests.ps1
Fixes #212 
This new resource adds the ability to connect a farm to an Office Online Server 2016/Office Web Apps 2013 farm.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/317)
> New SPOfficeOnlineServerBinding resource

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAccessServiceApp/MSFT_SPAccessServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPPerformancePointServiceApp/MSFT_SPPerformancePointServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPPerformancePointServiceApp/MSFT_SPPerformancePointServiceApp.schema.mof
- Tests/SharePointDsc/SharePointDsc.SPAccessServiceApp.Tests.ps1
- Tests/SharePointDsc/SharePointDsc.SPPerformancePointServiceApp.Tests.ps1
A couple of quick fixes to address issues:
* Access and PerformancePoint both had an incorrect type name in code, resulting in constant false test results
* PerformancePoint didn't have database name parameters, which in tandem with the above issue meant that you would see a new performance point service app created every time the DSC ran
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/326)
> Bugs with Access Services/Performance Point

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.psm1
- Tests/SharePointDsc/SharePointDsc.SPAlternateUrl.Tests.ps1
A quick fix here - the scenario is that if you use SPAlternateUrl, set to absent but still specify the URL property anyway, the test method will always return false. The URL property isn't mandatory and should be ignored in this scenario, this PR corrects that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/327)
> Fixed bug with URL property of SPAlternateUrl

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Tests/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
Fixes a quick bug where a defautl crawl account would not be reported correctly, causing an error in the get method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/337)
> Fixed bug with SPSearchServiceApp to allow mangement of default crawl account

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPRemoteFarmTrust/MSFT_SPRemoteFarmTrust.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPRemoteFarmTrust/MSFT_SPRemoteFarmTrust.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPRemoteFarmTrust.Tests.ps1
This PR adds a SPRemoteFarmTrust resource - this is used when trusting a remote farm for things such as federating search (as described at https://technet.microsoft.com/en-us/library/dn133749.aspx)
I've not added this to the main examples as its more of a niche thing, and when the revamped examples are done they will be added in for a resource specific example at that point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/368)
> Added SPRemoteFarmTrust resource

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1
Quick fix to something that should have happened in 1.1 when we removed Win32_Product from SPInstallPrereqs. I also made style changes to bring SPInstall in line as well. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/367)
> Removed Win32_Product from SPInstall

- Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.schema.mof
Missing required parameter CharacterSet in SPOutgoingEmailSettings example
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/369)
> Missing required parameter in example SPOutgoingEmailSettings

- CHANGELOG.md
- Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1
- Modules/SharePointDsc/Examples/Single Server/SharePoint.psd1
- Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1
- Modules/SharePointDsc/Examples/Small Farm/SharePoint.psd1
Added HostHeader parameters to Web application examples. This way multiple web applications can be created, without creating a blocker in IIS. Without this parameter, the website in IIS is created without host header and all other web applications won't be created due to an error.
- [N/A] Added/updated documentation and descriptions in .schema.mof files where appropriate?
- [N/A] New/changed code adheres to [Style Guidelines]?(https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- [N/A] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Added HostHeader parameters to Web application examples

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPCreateFarm.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPJoinFarm.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPPasswordChangeSettings.Tests.ps1
Fixes #375 - we do a check in the set methods now to ensure we aren't trying to create or join where an existing farm is there, warning the user that they must manually remove it first if the config is to be applied.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/376)
> Prevented SPCreateFarm and SPJoinFarm from executing sets when in a farm

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPQuotaTemplate.Tests.ps1
Fixing a scenario where the warning and limits are both 0, so really changing the -lt to a -le in the test method. Also brought it in line with the style guidelines and removed the $null return option from the get method.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/388)
> Fixed quote template test logic for equal warnings and limits

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md
- Modules/SharePointDsc/Examples/Resources/SPTrustedIdentityTokenIssuer/1-Example.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1
* Changed parameter ClaimsMappings in SPTrustedIdentityTokenIssuer to use an array of custom class MSFT_SPClaimTypeMapping 
* Changed SPTrustedIdentityTokenIssuer to throw an exception if certificate specified has a private key, since SharePoint doesn't accept it
* Fixed issue with SPTrustedIdentityTokenIssuer to stop if cmdlet New-SPTrustedIdentityTokenIssuer returns null
* Fixed issue with SPTrustedIdentityTokenIssuer to correctly get parameters ClaimProviderName and ProviderSignOutUri
* Fixed issue with SPTrustedIdentityTokenIssuer to effectively remove the SPTrustedAuthenticationProvider from all zones before deleting the SPTrustedIdentityTokenIssuer
* Updated code in SPTrustedIdentityTokenIssuer to respect style guidelines
---
This change is [<img …
> Improved and fixed multiple issues with resource SPTrustedIdentityTokenIssuer

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchResultSource.Tests.ps1
Added a more meaningful error to SPSearchResultSource when the enterprise search centre URL site collection doesn't exist
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/436)
> Fixed bug when search centre site doesn't exist

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPPerformancePointServiceApp/MSFT_SPPerformancePointServiceApp.psm1
Minor fix to excel services and performance point to add proxies to the default proxy group when they are provisioned.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/468)
> Fixed default proxy group issue

- .appveyor/appveyor.psm1
- .vscode/RunPesterTests.ps1
- CHANGELOG.md
Fixes #492 
Let me know if you think this will do it @ykuijs - the output should look like this:
> Failed test result summary:
> -----------------------------------------------------------
> 
> Context        : SharePointDsc whole of module tests
> Name           : Should not have errors in any markdown files
> Describe       : Validate example files
> FailureMessage : The variable '$mdIssuesPath' cannot be retrieved because it has not been set.
It'll loop and show all the failures in the one spot at the bottom of the test run.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/503)
> Added failed test summary to test runs

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchFileType/MSFT_SPSearchFileType.schema.mof
#542 
Updated the MOF schema of this resource to make serviceappName a key, instead of just required. Should resolve the issue that I had earlier.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/543)
> Updated MSFT_SPSearchFIleType.schema.mof to make ServiceAppName a Key

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1
I couldn't set WarningSiteCount as 0 because 0 is false in PowerShell. So I changed "if($params.WarningSiteCount)" to "if($params.WarningSiteCount) -ne $null".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/564)
> Bugfix in SPContentDatabase for setting WarningSiteCount as 0

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Tests.ps1
This fix will allow the search topology resource to remove components from a topology that don't have a server name (this happens when the server is removed from the farm).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/586)
> Fixed issue with search topology and servers that don't exist

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
Added an option to specify which service account should be used for the search and search host controller windows services to SPSearchServiceApp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/626)
> Added support to set windows search service accounts

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/readme.md
- Modules/SharePointDsc/Examples/Resources/SPServiceIdentity/1-Example.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPServiceIdentity.Tests.ps1
new resource, SPServiceInstanceIdentity
used to set SP services that support it (C2WTS, Sandbox service, Excel Services, etc..) to run on the server as a specified managed account, as descried in issue #577 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/642)
> new resource, SPServiceIdentity

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/readme.md
- Modules/SharePointDsc/Examples/Resources/SPManagedMetaDataServiceAppDefault/1-SetManagedMetadataDefault.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPManagedMetadataServiceAppDefault.Tests.ps1
New Resource to solve issue #674 .
The SPManagedMetadataServiceApp resource always sets the proxy as default for site collections and keywords. This behavior leads to issues in farms with several managed metadata service applications. A new resource SPManagedMetadataServiceAppDefault is used to set the defaults properly.
**Any chance anybody could run a integration test with the new resource. Currently my dev environment is not accessible.**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/699)
> New  resource "SPManagedMetadataServiceAppDefault" to solve issue 674

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/readme.md
When the SPAlternateUrl resource specifies Central Administration web app and the Default Zone, we should use Set-SPAlternateUrl to update the existing AAM instead of New-SPAlternateUrl to create a new one. Adding logic to handle this case. I have included notes in the readme with details of the new behavior, and a suggestion to use xWebsite from xWebAdministration to update IIS bindings since that's the only piece that Set-SPAlternateUrl does not touch.
I will take a look at the tests section, but would certainly appreciate some suggestions on how best to add test cases since I'm still getting up to speed on writing these.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharep …
> Additional support to allow SPAlternateUrl to update Default Zone URL for Central Administration

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPManagedMetadataServiceAppDefault.Tests.ps1
closes #779 .
Fixed usage of .GetType().FullName vs. TypeName.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/780)
> Fix SPManagedMetadataServiceApp - TypeName vs. .GetType().FullName

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1
This PR fixes a small bug: The variable used in Get-SPTimerJob for the web application was never set.
This is not a problem if a TimerJob is only rolled out on one webapplication, because then only one object is returned. However, as soon as the same TimerJob has been rolled out to more than one webapplication, activating/deactivating, for example, no longer works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/800)
> Fix: Timer jobs rolled out to multiple WebApps could not be configured via SPTimerJobState

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInfoPathFormsServiceConfig/MSFT_SPInfoPathFormsServiceConfig.psm1
This PR fixes a bug for setting the "MaxSizeOfUserFormState" for InfoPath Forms Services. If you've tried to set this parameter it was always throwing an error and the default value was (still) used.
The assignment was basically "current value = (current value * 1024)" before.
Not sure if someone could change the test too (not familiar with testing these things, sorry).
The test uses the default value of this service application. So even if the value wasn't changed with the Set method - the tests could never reveal that because of the default value that's tested against.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/836)
> Fix: SPInfoPathFormsServiceConfig - MaxSizeOfUserFormState parameter could never be set

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
Regarding issue MSFT_SPSearchContentSource does not take StartHour parameter for schedule #840
I was able to solve this issue, but I must admit that I am a newbie regarding the pull request process...
So here it is. From what I was able to understand, the StartHour parameter is correctly checked in the test Get-SPDSCSearchCrawlSchedule.psm1 module.
The issue seems to be in the MSFT_SPSearchContentSource.psm1, as in its Set-TargetResource function there is never the parameter CrawlScheduleStartDateTime which is required by the sharepoint powershell cmdlet Set-SPEnterpriseSearchCrawlContentSource to had a start hour to the schedule.
Hope it helps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Bugfix for issue 840 - SPSearchContentSource - StartHour parameter never updates anything - dev branch

- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.schema.mof
Fixed a mistake in the documentation — assuming the wiki is generated from this; if not, someone with access should update it.
(Does this need anything in changelog.md?)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/851)
> PsDscRunAsAccount should be PsDscRunAsCredential

- Tests/Integration/Azure/AzureEnvironmentBuilder.psm1
- Tests/Integration/Azure/template.json
Virtual Machines can have names of maximum 15 characters. Previously the VM name was concatenated using the resource group name and a postfix of up to 4 characters. This would leave only 11 characters for the resource group name which would only fail upon VM creation. Now the VMs have a fixed name (VM-dc/VM-sql/VM-sp)
Changed Find-AzureRmResource to Get-AzureRmResource as Find-AzureRmResource has been removed in Azure PowerShell 6.0.0
https://github.com/Azure/azure-powershell/releases/tag/v6.0.0-May2018
"Merge Get- and Find- functionality in Get-AzureRmResource"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> AzureEnvironmentBuilder: VM max name length and fix for Azure PowerShell 6.0.0

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
Fixes the problem where the CA service was not properly started in SPFarm when a non-english farm was used.
- Fixes #917 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/922)
> Fix Issue #917 for CA service instance naming

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Tests.ps1
Fixes an issue where some IndexLocation of existing environment had multiple values, which resulted in an array being returned. The new logic now returns the first directory, doesn't matter if its an array or a string. (Only Get-TargetResource is affected since this was a ReverseDSC discovered issue).
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/928)
> SPSearchTopology first partition

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1
Added support for detecting updated installation of Microsoft Visual C++ 2015/2017 Redistributable (x64) for SharePoint 2016 and SharePoint 2019.
Changed required version of Microsoft Visual C++ 2017 Redistributable (x64) to 14.13.26020.0 as this is the version included in the prerequisite installer.
- Fixes #959  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/964)
> SPInstallPrereq: Added support for detecting updated installation of VC++ redistributable

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1
This PR updates resource SPDistributedCacheService to avoid exception on Stop-SPServiceInstance with SharePoint 2019.
- https://github.com/PowerShell/SharePointDsc/issues/995: Resource SPDistributedCacheService throws an error when it configures the service for the 1st time. If I run the DSC configuration again on the server there is no error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/997)
> SPDistributedCacheService: Stop-SPServiceInstance may throw an exception in SharePoint 2019

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/readme.md
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1
Fixed issue where test resource never would return true for any configurations on SharePoint 2016/2019
Fixed issue where updating existing connection never would work for any configurations on SharePoint 2016/2019
Updated documentation to reflect that Force will not impact configurations for SharePoint 2016/2019. Updated the test method accordingly.
Partially fixes #1021 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1017)
> SPUserProfileSyncConnection: Fixes for SP2016 environments

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettings.Tests.ps1
Converted password for access account to secure string. Previsouly the resource would fail setting the password and an exeption was thrown that printed the password in clear text.
I would expect the password to already be a secure string, but apparently that's not the case.
- Fixes #1019 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1018)
> SPWebAppPeoplePickerSettings: Converted access account password to secure string

- CHANGELOG.md
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
I added a finally statement for the removal of the created session. Since in the Try section the value of the command is preceded by a return statement, the removal of the session is never executed when the command succeed.
Invoke-SPDSCCommand in SharePointDsc.Util.psm1 memory leak #1037
Not applicable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1042)
> Modules\SharePointDsc.Util: Bugfix Invoke-SPDSCCommand

- .vscode/GetTestCoverage.ps1
- .vscode/launch.json
- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProductUpdate.Tests.ps1
Added fixes for 1087.
New vscode launch settings to get code coverage reports for the currently selected unit test.
@ykuijs could you do a integration test of the changes in the SPProductUpdate Resource. I do not have a server which meets the prerequisites right now.
- Fixes #1087 
- Closes #1092 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1091)
> Fixed issue 1087 + vscode launch settings

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1
Added try-catch blocks around Get-Item. A terminating error for sources in weird file shares [particularly VMWare Workstation Shared Folders].
A bit against the guidelines: An empty catch-block because the result is only important if no terminating error happens. The `-ErrorAction SilentlyContinue` existed already for the command, though that doesn't catch terminating errors (as experienced in the linked issue). If the empty catch block really isn't wanted please tell me what to do in it.
- Fixes #1109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1112)
> Fixes PowerShell/SharePointDsc#1109

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
Fixed error when setting developer dashboard display level. The error resulted in the following error message:
PowerShell DSC resource MSFT_SPFarm  failed to execute Set-TargetResource functionality with error message: Exception setting "DisplayLevel": "Cannot convert null to type "Microsoft.SharePoint.Administration.SPDeveloperDashboardLevel" due to enumeration values that are not valid. Specify one of the following enumeration values and try again. The possible enumeration values are "Off,OnDemand,On"."
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1118)
> Fixed null exception for developer dashboard

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/readme.md
- Modules/SharePointDsc/Examples/Resources/SPManagedMetaDataServiceAppDefault/1-SetManagedMetadataDefault.ps1
- Modules/SharePointDsc/Examples/Resources/SPManagedMetaDataServiceAppDefault/2-ConfigureCustomProxyGroup.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPManagedMetadataServiceAppDefault.Tests.ps1
This PR updates the SPManagedMetadataServiceAppDefault resource to allow configuration of a default MMS Service App per Proxy Group. In the old version, it only allowed one default per farm, which is not correct.
This is however a breaking change, so will be merged into the v4.0 branch
- Fixes #1136 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1137)
> Implement fix for MMS Default issue

- CHANGELOG.md
- RequiredModules.psd1
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md
- SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1
Added possibility to specify path and thumbprint for the certificate so that it is impossible to inadvertently change the certificate on disk either by accident or maliciously. The certificate will be verified to match the specified thumbprint when importing using bot parameters.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1188)
> SPTrustedRootAuthority: Enable specifying both path and thumbprint

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedSecurityTokenIssuer/MSFT_SPTrustedSecurityTokenIssuer.psm1
- SharePointDsc/DSCResources/MSFT_SPTrustedSecurityTokenIssuer/readme.md
- tests/Unit/SharePointDsc/SharePointDsc.SPTrustedSecurityTokenIssuer.Tests.ps1
Added possibility to specify path and thumbprint for the certificate so that it is impossible to inadvertently change the certificate on disk either by accident or maliciously. The certificate will be verified to match the specified thumbprint when importing using bot parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1189)
> SPTrustedSecurityTokenIssuer: Added support for specifying both thumbprint and path

- CHANGELOG.md
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
Fixes an issue where Test-Resource would throw an error due to duplicate keys when a desired value is of type CimInstance[] and multiple values are specified, and the values are not in desired state.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1194)
> SharePointDSC General: Fixed duplicate key issue when testing resources

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
In function Set-TargetResource of resource SPTrustedIdentityTokenIssuer, test if property ClaimProviderName is omitted/null/empty, to call Get-SPClaimProvider only if necessary.
Fixes #1223 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1224)
> First run of DSC fails at SPTrustedIdentityTokenIssuer, if property ClaimProviderName is omitted/null/empty

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
Commit https://github.com/dsccommunity/SharePointDsc/commit/5d914d766663dd7b507fbcf4f7edf5aac016a472 introduced a regression in resource SPTrustedIdentityTokenIssuer:
Property ClaimProviderName is no longer actually set by Set-TargetResource, due to a bad test.
- Fixes #1227
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1228)
> Property ClaimProviderName is no longer actually set in resource SPTrustedIdentityTokenIssuer

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- SharePointDsc/DSCResources/MSFT_SPFarm/Readme.md
- tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
Added possibility to specify port number in the CentralAdministrationUrl parameter. Without this capability it is impossible to get a passing test for Central Administration site provisioned on a vanity URL and a port different from the URL scheme default port (80/443)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1238)
> SPFarm: Added possibility to specify port number in the CentralAdministrationUrl

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.psm1
Fixes an issue that blocked the usage of SPWebAppPolicy since version 4.4.0
The InputParameters parameter of Get-SPDscCacheAccountConfiguration was passed directly to Get-SPWebApplication and failed because InputParameters is an array of Object.
Changed the parameter to be the URL of the web application as that is the only use of that parameter.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1261)
> SPWebAppPolicy: Fixed incorrect parameter usage

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
Property SPTrustedLoginProvider.ProviderSignOutUri does not exist in SharePoint 2013 and it will cause an error if script attempts to set it.
So I added a test to not set it if current platform is SharePoint 2013.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1270)
> SPTrustedIdentityTokenIssuer: Do not set property ProviderSignOutUri in SP2013

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof
- tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1
SPUserProfileServiceApp
- Changed MySiteHostLocation parameter mandatory=$false
- Added validation to Set function for testing if SiteNamingConflictResolution parameter is defined then
also MySiteHostLocation parameters has to be because it is a mandatory parameter in the parameter set of New-SPProfileServiceApplication when SiteNamingConflictResolution is used
- Added "MySiteHostLocation" to Test-SPDscParameterState function in Test-TargetResource
- Fixes #1267 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1275)
> SPUserProfileServiceApp: Changed MySiteHostLocation parameter to not be mandatory

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1
- SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.schema.mof
- SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/readme.md
This resource is also able to set the properties FormsTokenLifetime, WindowsTokenLifetime and LogonTokenCacheExpirationWindow.
It checks for values leading to “The context has expired and can no longer be used.” errors.
The value for LogonTokenCacheExpirationWindow must be higher than the values for FormsTokenLifetime and WindowsTokenLifetime,
it will return an error if not.
- Fixes 1302
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1307)
> MSFT_SPSecurityTokenServiceConfig: Added properties FormsTokenLifetime, WindowsTokenLifetime and LogonTokenCacheExpirationWindow

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
I noticed this reboot and I don't see a good reason for it:
- SPS never requires the reboot of a server once it joined the farm using psconfigui.exe
- I took the time to test the suppression of the reboot with SharePoint Subscription / 2019 / 2016 / 2013: I could not notice any side effect, the server works normally as far as I could see
None
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1370)
> SPFarm: Suppress useless reboot triggered once a server joined the farm

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
Suppress a useless 5 minutes sleep triggered once a server joined the farm.
I tested it against SharePoint Subscription / 2019 / 2016 / 2013 and noticed no side effect
None
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1372)
> SPFarm: Suppress a useless 5 minutes sleep triggered once a server joined the farm

- CHANGELOG.md
- SharePointDsc/Modules/SharePointDsc.Farm/SPFarm.psm1
Fixes an regression bug with dashes '-' in configuration database names which made the helper function `Add-SPDscConfigDBLock` fail.
None
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1380)
> [SPFarm]Fix: Regression Bug Databasename with a dash

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
This PR Fixed issue where error 'You cannot call a method on a null-valued expression' was thrown when no MySiteHost was specified in the User Profile Service Application.
- Fixes #1306
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1412)
> SPUserProfileServiceApp: Fix issue where Get-TargetResource throws an error when no MySiteHost is specified

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1
Added `-Recurse` to `Get-ChildItem` when `Set-TargetResource` attempts to obtain reference to the certificate by thumbprint.
- Fixes #1417 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1418)
> SPTrustedRootAuthority - Fix Error while adding Trusted Root Authority via CertificateThumbprint

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
SharePoint Subscription introduced flighting. When creating a farm using PowerShell, one new step is to run cmdlet [Update-SPFlightsConfigFile](https://learn.microsoft.com/en-us/powershell/module/sharepoint-server/update-spflightsconfigfile?view=sharepoint-server-ps) to ensure that all flights in current build are registered in the configuration database.
In SharePoint Subscription, ensure that all flights available in current build are registered in the configuration database
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDs …
> [SPFarm] Ensure that flights are registered in SharePoint Subscription

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSearchCrawlerImpactRule/MSFT_SPSearchCrawlerImpactRule.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchCrawlerImpactRule.Tests.ps1
The Ressource threw an error if the Crawler Impact Rule did not exist. 
- Fixes #1444
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1445)
> SPSearchCrawlerImpactRule: Does throw if Rule does not exist.

- .vscode/launch.json
- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPSite.Tests.ps1
The Get Method failed to get an existing Site Collection on SharePoint Server Subscription Edition
- Fixes #1442
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1443)
> SPSite: Fix: SPSite Constructur returns $null when run as Ressource on SPSE
