dsccommunity/SharePointDsc

- Modules/xSharePoint/xSharePoint.psd1
Manually listed all cmdlets in Nested Modules in the psd1 CmdletsToExport property
> Fixes Issues with Nested Modules Cmdlets not Found. Closes #53

- Modules/xSharePoint/DSCResources/MSFT_xSPCreateFarm/MSFT_xSPCreateFarm.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPCreateFarm/MSFT_xSPCreateFarm.schema.mof
- Modules/xSharePoint/xSharePoint.psd1
Added the CentralAdministrationPort parameter to let users choose on what port to in off central administration
> added CentraladministrationPort parameter to MSFTt_xSPCreateFarm

- Modules/xSharePoint/DSCResources/MSFT_xSPSessionStateService/MSFT_xSPSessionStateService.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPSessionStateService/MSFT_xSPSessionStateService.schema.mof
- Tests/xSharePoint/xSharePoint.xSPSessionStateService.Tests.ps1
Added xSPSessionStateService DSC Resource to configure the
SPSessionStateService
> Addition of xSPSessionStateService

- Modules/xSharePoint/DSCResources/MSFT_xSPWebAppBlockedFileTypes/MSFT_xSPWebAppBlockedFileTypes.schema.mof
- Modules/xSharePoint/DSCResources/MSFT_xSPWebAppSiteUseAndDeletion/MSFT_xSPWebAppSiteUseAndDeletion.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPWebAppSiteUseAndDeletion/MSFT_xSPWebAppSiteUseAndDeletion.schema.mof
- Modules/xSharePoint/xSharePoint.pssproj
- README.md
- Tests/Tests.pssproj
- Tests/xSharePoint/xSharePoint.xSPWebAppSiteUseAndDeletion.Tests.ps1
New xSPWebAppSiteUseAndDeletion resource, as mentioned in issue #112. Please review and let me know your comments.
Includes a small update in the mof file of the Blocked File Types resource
> New xSPWebAppSiteUseAndDeletion resource

- Modules/xSharePoint/DSCResources/MSFT_xSPSubscriptionSettingsServiceApp/MSFT_xSPSubscriptionSettingsServiceApp.psm1
- Tests/xSharePoint/xSharePoint.xSPSubscriptionSettings.Tests.ps1
> Missing xSPSubscriptionSettingsProxy fix

- Modules/xSharePoint/DSCResources/MSFT_xSPWebApplication/MSFT_xSPWebApplication.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPWebApplication/MSFT_xSPWebApplication.schema.mof
- README.md
Adding SSL support to address issue #179 
@camiloborges @anlynes @caadam Code review time boys
> Added SSL support to xSPWebApplication

- Modules/xSharePoint/DSCResources/MSFT_xSPSearchServiceApp/MSFT_xSPSearchServiceApp.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPSearchServiceApp/MSFT_xSPSearchServiceApp.schema.mof
- README.md
- Tests/xSharePoint/xSharePoint.xSPSearchServiceApp.Tests.ps1
@camiloborges @anlynes @caadam Code review time boys
> Added support to xSPSearchServiceApp for default crawl account

- Modules/xSharePoint/DSCResources/MSFT_xSPWebApplication/MSFT_xSPWebApplication.psm1
- README.md
Quickie code review @camiloborges @anlynes @caadam @ykuijs
> Fixed issue with kerberos and anon auth

- Modules/xSharePoint/DSCResources/MSFT_xSPUserProfileSyncConnection/MSFT_xSPUserProfileSyncConnection.psm1
- README.md
@camiloborges Review for you mate after we talked about this one already
> Fixed bug with UPS Connection

- Modules/xSharePoint/DSCResources/MSFT_xSPManagedAccount/MSFT_xSPManagedAccount.psm1
- README.md
@ykuijs @camiloborges @anlynes @caadam Can a brother get a code review for a grand total of 4 lines of code!
> Fixed bug with schedule of managed accounts

- Modules/xSharePoint/DSCResources/MSFT_xSPSearchContentSource/MSFT_xSPSearchContentSource.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPSearchContentSource/MSFT_xSPSearchContentSource.schema.mof
- Modules/xSharePoint/Modules/xSharePoint.Search/xSPSearchContentSource.Schedules.psm1
- README.md
- Tests/Stubs/SharePoint/16.0.4316.1217/Microsoft.SharePoint.PowerShell.psm1
- Tests/xSharePoint/xSharePoint.xSPSearchContentSource.Tests.ps1
- appveyor.yml
@camiloborges @anlynes @caadam @ykuijs Code review time boys
> Added search content source resource

- Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.psm1
- README.md
@caadam I save the easy reviews for you mate. Check this one real quick for me bloke.
> Changed xSPInstallPreReqs test for AD RM to 2.*

- Modules/xSharePoint/DSCResources/MSFT_xSPServiceAppSecurity/MSFT_xSPServiceAppSecurity.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPServiceAppSecurity/MSFT_xSPServiceAppSecurity.schema.mof
- README.md
- Tests/xSharePoint/xSharePoint.xSPServiceAppSecurity.Tests.ps1
@caadam @camiloborges  @anlynes @ykuijs Code review time - new resource to manage the administrator and sharing permissions on any service app.
> Added xSPServiceAppSecurity resource

- .vscode/launch.json
- Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.schema.mof
- README.md
- Tests/xSharePoint/xSharePoint.xSPCacheAccounts.Tests.ps1
@ykuijs - Seeing as we discussed this one can I get you to review this one?
> Fixed bug with claims accounts in xSPCacheAccounts

- Modules/xSharePoint/DSCResources/MSFT_xSPDistributedCacheService/MSFT_xSPDistributedCacheService.psm1
@caadam 2 second code review bloke
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/250)
> Fixed an ordinary bit of code in the xSPDistributedCacheService

- Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1
- README.md
@caadam - another quickie mate, fix for #248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/253)
> Fixed output of get method for xSPUsageApplication

- README.md
- appveyor.yml
@caadam @ykuijs @camiloborges - Code review time. Fix for issue #249 included. I've tested with this script from my personal AppVeyor feed
register-psrepository -Name BrFarnxSharePointDev -SourceLocation https://ci.appveyor.com/nuget/xsharepoint-yu1ffgpjs149
find-module -name xSharePoint -Repository BrFarnxSharePointDev -RequiredVersion 0.12.738.0 | Install-Module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/252)
> Fixed issue with develoepr nuget feed from AppVeyor

- Modules/xSharePoint/DSCResources/MSFT_xSPInstall/MSFT_xSPInstall.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.psm1
- README.md
@caadam @camiloborges @anlynes @ykuijs - Code review, feedback on prereq installer
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/246)
> Fixed issue with reboot detection and reutrn of get method in xSPInstallPrereqs

- Modules/xSharePoint/DSCResources/MSFT_xSPUsageApplication/MSFT_xSPUsageApplication.psm1
- README.md
- Tests/xSharePoint/xSharePoint.xSPusageApplication.Tests.ps1
@caadam @ykuijs @camiloborges @anlynes - Code review time, this is the fix for #247
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/254)
> Added provisioning of proxy to xSPUsageApplication

- Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.schema.mof
- README.md
- Tests/xSharePoint/xSharePoint.xSPInstallPrereqs.Tests.ps1
added SXSpath parameter to xSPInstallPrereqs to support installation of prerequisite windows features in offline environments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/259)
> issue #243: support for offline feature installation

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Fixes #263
Please see [this issue](https://github.com/PowerShell/DscResources/issues/112) for further details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/264)
> Add .GitHub Template documents - Fixes #263

- Modules/xSharePoint/DSCResources/MSFT_xSPExcelServiceApp/MSFT_xSPExcelServiceApp.psm1
- Tests/xSharePoint/xSharePoint.xSPExcelServiceApp.Tests.ps1
@caadam @camiloborges @ykuijs @anlynes - Code review time, quick fix for Excel services (it only just got added in this release, so no addition to the readme file as it's added there already as a new resource). This is a fix for #251 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/265)
> Fixed bug with excel services type name

- Modules/xSharePoint/DSCResources/MSFT_xSPDistributedCacheService/MSFT_xSPDistributedCacheService.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPFarmSolution/MSFT_xSPFarmSolution.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPSearchContentSource/MSFT_xSPSearchContentSource.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPSearchTopology/MSFT_xSPSearchTopology.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPUserProfileSyncService/MSFT_xSPUserProfileSyncService.psm1
- README.md
- fixes #257 
@anlynes @camiloborges @caadam @ykuijs Code review boys
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/267)
> Added timestamps to verbose logging

- .github/ISSUE_TEMPLATE.md
Updating the Issue Template as per this discussion: https://github.com/PowerShell/DscResources/issues/112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/276)
> Updated Issue Template

- Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.psm1
- Modules/xSharePoint/DSCResources/MSFT_xSPInstallPrereqs/MSFT_xSPInstallPrereqs.schema.mof
- README.md
- Tests/xSharePoint/xSharePoint.xSPInstallPrereqs.Tests.ps1
Fixes #229 - @ykuijs @camiloborges @anlynes Code review time guys. Just made changes to xSPInstallPrereqs to work with the RTM release of SP2016
- [N/A] Examples updated for both the single server and small farm templates in the examples folder?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/279)
> Fixed prereqs for SP2016 RTM

- Modules/xSharePoint/DSCResources/MSFT_xSPCacheAccounts/MSFT_xSPCacheAccounts.psm1
- Tests/xSharePoint/xSharePoint.xSPCacheAccounts.Tests.ps1
@camiloborges @ykuijs @caadam  @anlynes - Code review. Found a minor bug working with Andrew on the cache accounts when the property bag values aren't set in claims format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/xsharepoint/288)
> Bug fix for claims accounts in cache values

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.schema.mof
- Tests/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1
This one addresses #321 - quick fix to set which compatibility level to deploy a solution as. 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/325)
> Support compatibility level option for SPFarmSolution

- .vscode/RunGlobalTests.ps1
- .vscode/ScriptAnalyzerSettings.psd1
- Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmAdministrators/MSFT_SPFarmAdministrators.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPHealthAnalyzerRuleState/MSFT_SPHealthAnalyzerRuleState.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/MSFT_SPUserProfileProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSection/MSFT_SPUserProfileSection.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/MSFT_SPWorkManagementServiceApp.psm1
- Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1
- Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1
- Tests/SharePointDsc.TestHarness.psm1
- Tests/SharePointDsc/SharePointDsc.Global.Tests.ps1
- Tests/SharePointDsc/SharePointDsc.TestHelpers.psm1
Fixes #309 - addresses the use of aliases throughout the resource. Also picked up some of the $null checks in the files I touched, and a couple of minor compile errors in the example files seeing as the script analyser had issues with them.
- [n/a] Change details added to Unreleased section of readme.md?
- [n/a] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> Fixed up use of PowerShell aliases

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
A quick touch up that should have been included in PR #330 that relates to issue #329 
Minor change to use correct property names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/334)
> Incorrect properties missed from #330

- Modules/SharePointDsc/Modules/SharePointDsc.Search/SPSearchContentSource.Schedules.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
Fixes #310
Fixed minor internal references to output type messages from the script analyser.
- [n/a] Change details added to Unreleased section of readme.md?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/336)
> Fixed output type errors from PSScriptAnalyser

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Modules/SharePointDsc/SharePointDsc.psd1
- Tests/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1
Fixes #293 and is a cleaned up version of #341 as discussed in the comments there
@ykuijs all yours to review mate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/343)
> Removed Win32_Product from SPInstallPrereqs

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
- appveyor.yml
Updating version numbers before I branch out for the 1.1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/346)
> Prep for 1.1 release

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Modules/SharePointDsc/SharePointDsc.psd1
- Tests/SharePointDsc/SharePointDsc.SPServiceAppSecurity.Tests.ps1
- Tests/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1
Fixes #348 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/351)
> Fix issue with group names in claims tokens

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Fixes #312 - A quick change to the module manifest
- [n/a] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/352)
> Fixed unnecessary wildcards in manifest

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/MSFT_SPAppCatalog.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPCacheAccounts/MSFT_SPCacheAccounts.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPDatabaseAAG/MSFT_SPDatabaseAAG.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPIrmSettings/MSFT_SPIrmSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedAccount/MSFT_SPManagedAccount.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPPasswordChangeSettings/MSFT_SPPasswordChangeSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchCrawlRule/MSFT_SPSearchCrawlRule.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTimerJobState/MSFT_SPTimerJobState.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/MSFT_SPWorkManagementServiceApp.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Search/SPSearchContentSource.Schedules.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.BlockedFileTypes.psm1
- Tests/Generate-SPDscHelpFiles.ps1
- Tests/Generate-SPDscWikiPages.ps1
- Tests/SharePointDsc/SharePointDsc.SPAlternateUrl.Tests.ps1
Fixes #311 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/353)
> Swapped all null values to the left of comparissons

- CHANGELOG.md
- appveyor.yml
A fix to appveoyr as per [issue 147 on the main DscResource repo](https://github.com/PowerShell/DscResources/issues/147)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/359)
> Removed chocolatey for pester install

- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Updates to the templates for GitHub integration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/362)
> Updated github templates

- .vscode/RunPesterTests.ps1
- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmAdministrators/MSFT_SPFarmAdministrators.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/MSFT_SPUserProfileProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSection/MSFT_SPUserProfileSection.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppBlockedFileTypes/MSFT_SPWebAppBlockedFileTypes.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppGeneralSettings/MSFT_SPWebAppGeneralSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppThrottlingSettings/MSFT_SPWebAppThrottlingSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppWorkflowSettings/MSFT_SPWebAppWorkflowSettings.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.BlockedFileTypes.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.GeneralSettings.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Throttling.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Workflow.psm1
- Modules/SharePointDsc/SharePointDsc.psd1
- Tests/Unit/SharePointDsc.TestHarness.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSection.Tests.ps1
- appveyor.yml
Fixes #313 as well as fixes style use in the documents that were touched.
- [n/a] [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/364)
> Removed plural noun use

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchResultSource.Tests.ps1
Added a new resource that can be used to set up and configure result sources for a specified search service application. Again I'm leaving the examples for the refactor that I have in progress on another branch rather than double the work here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/373)
> Added SPSearchResultSource resource

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/377)
> Release prep for 1.2

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Tests.ps1
Fixes #365 
This fix makes the detection of topology depend on server IDs instead of names, resolving the issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/379)
> Fixed issue with search topology

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1
Fixing typo within SPServiceAppProxyGroup resource
Fixing comparison operator in SPJoinFarm resource (issue #381)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/392)
> fixed typos in SPJoinFarm and SPServiceAppProxyGroup

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
- appveyor.yml
Updating version numbers to release 1.3
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/408)
> Prep for 1.3 release

- Modules/SharePointDsc/SharePointDsc.psd1
there was a typo in the word "Covers" in the PSD1 file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/416)
> Fixes typo in description for PowerShell Gallery

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPInstallLanguagePack.Tests.ps1
Fix SPInstallLanguagePack to install before farm creation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/413)
> Fix SPInstallLanguagePack to install before farm creation

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPVisioServiceApp.Tests.ps1
Now creates the Service App Proxy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/411)
> SPVisioServiceApplication Fix

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.psm1
Fix SPServiceInstance with GetType Method
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/434)
> Fix SPServiceInstance with GetType Method

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPManagedMetadataServiceApp.Tests.ps1
Fixes #232 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/437)
> Added content type hub URL support for existing apps

- .appveyor/appveyor.psm1
- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/440)
> Increment version for 1.4 release

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1
Fix Get-TargetResource of SPManagedMetaDataServiceApp resource
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/446)
> Fix Get-TargetResource of SPManagedMetaDataServiceApp resource

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Fixing a test issue by adding the minimum required version of PowerShell to the module manifest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/448)
> Fixed module manifest required version property

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
Fixes #444
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/449)
> Fixed bug with case of server names

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPCreateFarm.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPJoinFarm.Tests.ps1
- Tests/Unit/Stubs/SharePoint/16.0.4456.1000/Microsoft.SharePoint.PowerShell.psm1
Fixes #450 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/451)
> Added feature pack 1 support

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/MSFT_SPAppCatalog.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/readme.md
- Tests/Unit/SharePointDsc/SharePointDsc.SPAppCatalog.Tests.ps1
Fixes #386 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/470)
> Added access denied error trap to give more info on failure of SPAppCatalog

- .appveyor/appveyor.psm1
- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/MSFT_SPAppCatalog.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPAppCatalog/readme.md
- Modules/SharePointDsc/SharePointDsc.psd1
- Tests/Unit/SharePointDsc/SharePointDsc.SPAppCatalog.Tests.ps1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/469)
> Prep for v1.5 release

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/Readme.md
Updated documentation in regards to supported scenarios for installation of binaries from network locations. The short version is it's doable, but only at the expense of security, so I wanted to capture that and make it clear in the documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/473)
> Updated documentation on remote installation

- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPPublishServiceApplication/MSFT_SPPublishServiceApplication.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceInstance/MSFT_SPServiceInstance.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPAppCatalog.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPJoinFarm.Tests.ps1
This is a quick PR to fix the issues we found after the new version of pester was released, so we can unblock PR #491
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/499)
> Fixes after new Pester release

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
Fixes #255 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/500)
> Fixed context creation for search service app

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
Fixes #490
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/501)
> Fixed wait time in SPSearchTopology

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1
Fixed issue with SPWebAppPolicy resource and OS in non-EnUS language
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/504)
> Fix SPWebAppPolicy with OS in non-EnUS language

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1
#544 
I added a loopCount which increments every 5 seconds, and counts up to 600 == 30m (20/m)
This will timeout the SPFarmSolution after 30 minutes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/552)
> Added a loopcount increments every 5s to 600 before breaking the loop.

- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
Fixing verbose message that identifies SP2016
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/568)
> Fixing verbose message that identifies SP2016

- CHANGELOG.md
Changelog addition for pull req 568
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/569)
> Fixing verbose message that identifies SP2016 as 2013 in MSFT_SPFarm

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.schema.mof
- Modules/SharePointDsc/Examples/Resources/SPManagedMetaDataServiceApp/3-SetTermStoreAdmins.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPManagedMetadataServiceApp.Tests.ps1
Adds support to SPManagedMetadataServiceApp to set term store admins
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/578)
> Add support to SPManagedMetadataServiceApp to set term store admins

- CHANGELOG.md
- Modules/SharePointDsc/Modules/SharePointDsc.Farm/SPFarm.psm1
Fixes #581 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/588)
> Fixed bug with - in names of farm config DB

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/590)
> Prep for 1.7 release

- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1
Quick fix for a bug I introduced in 1.7, I forgot to test the new MMS scenario, only updating existing ones, so thats my bad.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/598)
> Bug fix for new MMS

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPDesignerSettings/MSFT_SPDesignerSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPOutgoingEmailSettings/MSFT_SPOutgoingEmailSettings.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSubscriptionSettingsServiceApp/MSFT_SPSubscriptionSettingsServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPermissions/MSFT_SPWebAppPermissions.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPExcelServiceApp.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPInstallLanguagePack.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPOutgoingEmailSettings.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSubscriptionSettings.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplication.Tests.ps1
Bugfixes for issues #540, #558, #561, #580, #587, #589, #594, #596 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/600)
> Another bugfix rollup

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPServiceAppProxyGroup.tests.ps1
update to fix Issue #606  
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/608)
> fix SPServiceAppProxyGroup resource to use DisplayName property instead of Name

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPBlobCacheSettings/MSFT_SPBlobCacheSettings.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPCreateFarm/MSFT_SPCreateFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPJoinFarm/MSFT_SPJoinFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPQuotaTemplate/MSFT_SPQuotaTemplate.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPRemoteFarmTrust/MSFT_SPRemoteFarmTrust.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSessionStateService/MSFT_SPSessionStateService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/MSFT_SPUserProfileProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSiteUseAndDeletion/MSFT_SPWebAppSiteUseAndDeletion.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/MSFT_SPWorkManagementServiceApp.psm1
- Modules/SharePointDsc/Examples/Resources/SPUserProfileServiceApp/2-NoILMUsed.ps1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebAppPolicy/SPWebAppPolicy.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.GeneralSettings.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProductUpdate.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPQuotaTemplate.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPShellAdmins.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPolicy.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppSiteUseAndDeletion.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWorkManagementServiceApp.Tests.ps1
Implemented several bugfixes for the following issues:
#621, #618, #614, #610, #605, #602, #611, #609, #464, #622, #613
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/630)
> Yet another bugfix Rollup

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
- appveyor.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/631)
> Preparing to release v1.8

- Tests/Integration/Azure/AzureEnvironmentBuilder.psm1
- Tests/Integration/Azure/CustomScripts/DevSetup.ps1
- Tests/Integration/Azure/DscConfigs/DomainController.ps1
- Tests/Integration/Azure/DscConfigs/SQLServer.ps1
- Tests/Integration/Azure/DscConfigs/SharePointPrep.ps1
- Tests/Integration/Azure/template.json
This change adds cmdlets that can be used to automate creation of a dev environment in Azure. There is some basic doco in the PowerShell comments for this, but I'll also author a wiki page with the content in more detail there to demonstrate it's use, but in short it will give you the following in to a new resource group:
* Domain controller with all required service accounts
* SQL Server with SQL configured as required for SP
* SharePoint box with SharePoint installed (no farm configured) and dev tools (VS Code, git, etc.) installed 
My plans for this going forward also include automating the deployment of the integration tests so that we can more easily run those in a consistent fashion, but this should at least help people get started on the dev side of things too.
---
This change …
> Create Azure dev environment

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Thanks for submitting a Pull Request to this project.
This template will help you create your pull request.
Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).
To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
**DELETE THIS LINE AND ABOVE**
[Replace this with a description of your pull request]
**DELETE THIS LINE AND BELOW**
Your contribution to this project is greatly appreciated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/651)
> Updates to prepare for release 1.9

- Tests/TestHarness.psm1
This is pushing a fix that @ykuijs made in the release branch for 1.9 back in to dev to resolve issues there.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/654)
> Fix for test harness issue

- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Tests.ps1
Fixes for Issues 487 and 519
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/658)
> Fixed Issues 487 and 519

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPMinRoleCompliance/MSFT_SPMinRoleCompliance.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPMinRoleCompliance/MSFT_SPMinRoleCompliance.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPMinRoleCompliance/readme.md
- Modules/SharePointDsc/Examples/Resources/SPMinRoleCompliance/1-EnsureCompliance.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPMinRoleCompliance.Tests.ps1
This resource is used to ensure that at any given point in time a farm that is using MinRole based roles will be compliant for the service instances that it runs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/653)
> SPMinRoleCompliance resource

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.schema.mof
- Modules/SharePointDsc/Examples/Resources/SPWeb/2-EnableAccessRequests.ps1
- Modules/SharePointDsc/Examples/Resources/SPWeb/3-DisableAccessRequests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWeb.Tests.ps1
Closes #539 .
Extended the SPWeb resource with the ability to change the request access mail address.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/667)
> Extend SPWeb with the ability to change the email address for access requests

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/readme.md
- Modules/SharePointDsc/Examples/Resources/SPWebAppSuiteBar/1-ApplySuiteBarBranding2016.ps1
- Modules/SharePointDsc/Examples/Resources/SPWebAppSuiteBar/2-ApplySuiteBarBranding2013.ps1
- Modules/SharePointDsc/Examples/Single Server/SharePoint.ps1
- Modules/SharePointDsc/Examples/Small Farm/SharePoint.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppSuiteBar.Tests.ps1
- ✔ Change details added to Unreleased section of changelog.md?
- ✔ Added/updated documentation and descriptions in .schema.mof files where appropriate?
- ✔ Examples updated for both the single server and small farm templates in the examples folder?
- ✔ New/changed code adheres to [Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md)?
- ✔ [Unit and Integration tests](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md) created/updated where possible?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/662)
> Added the new SPWebAppSuiteBar resource to edit Web App Suite Bar branding

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1
This PR is to fix the issue #676 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/677)
> Fixed resource SPWebApplicationExtension, which uses wrong object to return property AllowAnonymous

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkflowService/MSFT_SPWorkflowService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkflowService/MSFT_SPWorkflowService.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkflowService/readme.md
- Modules/SharePointDsc/Examples/Resources/SPWorkflowService/1-RegisterWorkflowService.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWorkflowService.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWorkflowService.ps1
Added a new resource to register a SharePoint farm against a Workflow Service instance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/694)
> New Resource SPWorkflowService

- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerADResourcePoolSync/MSFT_SPProjectServerADResourcePoolSync.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerADResourcePoolSync/MSFT_SPProjectServerADResourcePoolSync.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerAdditionalSettings/MSFT_SPProjectServerAdditionalSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerAdditionalSettings/MSFT_SPProjectServerAdditionalSettings.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerGlobalPermissions/MSFT_SPProjectServerGlobalPermissions.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerGlobalPermissions/MSFT_SPProjectServerGlobalPermissions.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerGroup/MSFT_SPProjectServerGroup.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerGroup/MSFT_SPProjectServerGroup.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerPermissionMode/MSFT_SPProjectServerPermissionMode.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerTimeSheetSettings/MSFT_SPProjectServerTimeSheetSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerTimeSheetSettings/MSFT_SPProjectServerTimeSheetSettings.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerUserSyncSettings/MSFT_SPProjectServerUserSyncSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerUserSyncSettings/MSFT_SPProjectServerUserSyncSettings.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerWssSettings/MSFT_SPProjectServerWssSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerWssSettings/MSFT_SPProjectServerWssSettings.schema.mof
- Modules/SharePointDsc/Modules/SharePointDsc.ProjectServer/ProjectServerConnector.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.ProjectServerConnector.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerADResourcePoolSync.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerAdditionalSettings.tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerGlobalPermissions.tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerGroup.tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerTimeSheetSettings.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerUserSyncSettings.tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerWssSettings.tests.ps1
I broke a couple of things in these resources with the kerberos fixes - my bad! Fixes are here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/692)
> Project server bug

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheService.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1
Implemented fix for issue #681 and included fix from PR #687
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/697)
> Fixed issue 681 and included PR 687

- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1
Fixes an issue with the User Profile Sync Service
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/698)
> Fix - Issue #696

- Modules/SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceAppDefault/MSFT_SPManagedMetadataServiceAppDefault.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPMinRoleCompliance/MSFT_SPMinRoleCompliance.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/MSFT_SPWebAppAuthentication.psm1
Issue in previous Prep PR
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/701)
> Release 2.0prep

- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
Fixes Issue #703
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/704)
> Fix for Get-TargetResource

- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
Added a new utility function to support the extraction of well formatted Office Patch GUID.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/708)
> Added the Format-OfficePatchGuid

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceAppPermissions/MSFT_SPUserProfileServiceAppPermissions.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceAppPermissions/MSFT_SPUserProfileServiceAppPermissions.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceAppPermissions.Tests.ps1
Fix for Issue #612 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/735)
> Fix issue 612

- CHANGELOG.md
- Tests/Integration/Azure/AzureEnvironmentBuilder.psm1
- Tests/Integration/Azure/DscConfigs/SharePointPrep.ps1
- Tests/Integration/Azure/template.json
Updated the `template.json` to use the `reference` function to obtain the storage account url. Also updated the SharePointPrep config to pass in the Azure environment that the user is currently logged into.
Fixes #747 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/750)
> Made Azure dev scripts work in any Azure environment

- CHANGELOG.md
- Tests/Integration/Azure/DscConfigs/SQLServer.ps1
Updated the SQLServer config file for the Azure lab to use SqlServerDsc version 10.0.0.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/758)
> Updated to use SqlServerDsc version 10.0.0.0

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPAlternateUrl/readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/MSFT_SPServiceIdentity.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceIdentity/readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPAlternateUrl.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPServiceIdentity.Tests.ps1
Implemented fixed for issues #746, #743, #739, #732 and #725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/757)
> Bugfix rollup PR

- Modules/SharePointDsc/DSCResources/MSFT_SPMinRoleCompliance/MSFT_SPMinRoleCompliance.psm1
Exports the Get-SPDscRoleTestMethod function
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/761)
> Fix issue 760

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPVisioServiceApp/MSFT_SPVisioServiceApp.psm1
Fixes issue #772 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/773)
> Fixes Visio SA issue

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
v2.2 prep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/784)
> Preparation for the release of v2.2

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.schema.mof
- Modules/SharePointDsc/Examples/Resources/SPUserProfileServiceApp/1-Example.ps1
- Modules/SharePointDsc/Examples/Resources/SPUserProfileServiceApp/2-NoILMUsed.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileServiceApp.Tests.ps1
Fixing issue #770 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/787)
> Fixes for MySiteHostLocation and Managed Path

- appveyor.yml
Test to see what happens if we don't specify an image in the AppVeyor.yml file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/806)
> Update AppVeyor.yml image

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1
Another bugfix rollup PR, fixing issues #774, #794, #795, #804, #809
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/811)
> Bugfix Rollup

- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1
Thanks for submitting a Pull Request to this project.
This template will help you create your pull request.
Please make sure you have read the [Contribution Guidelines](https://github.com/powershell/xSharePoint/wiki/Contributing%20to%20xSharePoint).
To aid community reviewers in reviewing and merging your PR, please take the time to run through this checklist:
**DELETE THIS LINE AND ABOVE**
[Replace this with a description of your pull request]
**DELETE THIS LINE AND BELOW**
Your contribution to this project is greatly appreciated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/814)
> Fixes for Connection Display Name

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparation steps for v2.3 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/820)
> Release 2.3prep

- CHANGELOG.md
- appveyor.yml
Setting up branch for new version
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/822)
> Setting up branch for new version

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchContentSource.Tests.ps1
Added support for Line of Business (LoB) content sources in the SPSearchContentSource resource. Issue #830 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/831)
> Added support for LoB Content Sources

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/readme.md
- Tests/Unit/SharePointDsc/SharePointDsc.SPProductUpdate.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchContentSource.Tests.ps1
This PR includes fixes for issues #797, #827, #832, #834, #835 and #837
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/838)
> Bugfixes for issues 797, 827, 832, 834, 835 and 837

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
v2.4 preparations
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/843)
> v2.4 release preparations

- Tests/Unit/Stubs/SharePoint/16.0.10711.37301/Microsoft.SharePoint.PowerShell.psm1
added PP stubs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/854)
> Added stubs from Public Preview

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSiteUrl/MSFT_SPSiteUrl.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSiteUrl/MSFT_SPSiteUrl.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSiteUrl/readme.md
- Modules/SharePointDsc/Examples/Resources/SPSiteUrl/1-Example.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSiteUrl.Tests.ps1
Added new SPSiteURL resource to the module
@NikCharlebois Can you review, so it can be included in the release of next Wednesday?
- Fixes #808 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/862)
> SPSiteURL: Added new resource

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparations for v2.5 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/864)
> Preparations for v2.5 release

- appveyor.yml
Update appveyor.yml after release of v2.5
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/866)
> Updated appveyor.yml to v2.6

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchContentSource.Tests.ps1
Fixes issue 867 by changing the way we obtain the search content source by name.
- Fixes #867 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/868)
> Fixed issue 867

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppSuiteBar.Tests.ps1
Changed the Test-TargetResource method so that the verification checks the relevant values. Added test to verify the error reported in #883 
- Fixes #883 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/888)
> SPWebAppSuiteBar: Fixed incorrect test method that resulted in the resource to not work

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSite.Tests.ps1
Uses the central administration site system account token to create a new instance of the site collection when creating default groups
Previously this resource retrieved the SPSite using Get-SPSite. For some reason the owner and secondary owner properties can then be null. This leads to the Test-TargetResource always returning false. If the site is instantiated using the central administration system account user token the owner and secondary owner properties are populated.
Fixes #898
Fixes #875 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/904)
> SPSite: Fixed permission issues for default group creation.

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchManagedProperty/MSFT_SPSearchManagedProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchResultSource.Tests.ps1
Allows the SPResultSource resource to create local sources.
- Fixes #869 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/909)
> Fix Issue #869

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchManagedProperty/MSFT_SPSearchManagedProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchManagedProperty/MSFT_SPSearchManagedProperty.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchManagedProperty.Tests.ps1
Fix Issues with Aliases and Crawled Property Mapping
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/919)
> Fix Issues with Aliases and Crawled Property Mapping

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof
Add parameter UseWReplyParameter to resource SPTrustedIdentityTokenIssuer
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/934)
> Added parameter UseWReplyParameter

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Updates in preparation of v2.6 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/941)
> Prep for v2.6 release

- appveyor.yml
Increased version to v2.7 in appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/943)
> Increased version to v2.7 in appveyor.yml

- CHANGELOG.md
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
- Tests/Unit/Stubs/SharePoint/16.0.10337.12109/Microsoft.SharePoint.PowerShell.psm1
Fix the last issues with the new SP2019 stubs
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/948)
> Fix issues with new SP2019 stubs

- .vscode/launch.json
- CHANGELOG.md
Added support for SP2019 to launch.json
Fixed a problem with the VSCode launch.json file
- Fixes #956 
- [] Resource documentation added/updated in README.md in the resource folder.
- [] Resource parameter descriptions added/updated in schema.mof
- [] Comment-based help added/updated.
- [] Localization strings added/updated in all localization files as appropriate.
- [] Examples appropriately added/updated.
- [] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [] Integration tests added/updated (where possible). See [DSC Resource Testing …
> Fixed VSCode launch.json to run all unit tests; Added SP2019 setting

- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppBlockedFileTypes/MSFT_SPWebAppBlockedFileTypes.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppGeneralSettings/MSFT_SPWebAppGeneralSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppThrottlingSettings/MSFT_SPWebAppThrottlingSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppWorkflowSettings/MSFT_SPWebAppWorkflowSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
Latest changes in parameter name broke the Get-TargetResource, where the URL is no longer returned.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/958)
> Get-Target resource fix for SPWebApplication

- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.schema.mof
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchResultSource.Tests.ps1
Need to add ScopeURL as a key because multiple SPWeb can have a result source with the same name.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/965)
> Added ScopeURl as key

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparations for the release of v3.0
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/967)
> Release v3.0 preparations

- CHANGELOG.md
- LICENSE
Update LICENSE file to match the Microsoft Open Source Team standard.
- Fixes #969 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/970)
> SharePointDsc: Update LICENSE file to match the Microsoft Open Source Team standard. Fixes Issue #969

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceSettings/MSFT_SPSearchServiceSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceSettings/MSFT_SPSearchServiceSettings.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceSettings/readme.md
- Modules/SharePointDsc/Examples/Resources/SPSearchServiceSettings/1-ConfigureSettings.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceSettings.Tests.ps1
This PR adds a new resource SPSearchServiceSettings
- Fixes #923 
- Fixes #974 
- Fixes #966 
- Fixes #986 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/978)
> New resource: SPSearchServiceSettings

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparations for v3.1 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/988)
> Preparations for v3.1 release

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPInstallPrereqs/MSFT_SPInstallPrereqs.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/MSFT_SPSearchResultSource.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchResultSource/readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/readme.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchResultSource.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPServiceAppSecurity.Tests.ps1
This PR fixes several localization issues that were discovered when using non-English versions of Windows and/or SharePoint
- Fixes #920 
- Fixes #955 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/993)
> Bugfix PR: Fixing localization issues

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPMinRoleCompliance/MSFT_SPMinRoleCompliance.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProductUpdate/MSFT_SPProductUpdate.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPProjectServerGroup/MSFT_SPProjectServerGroup.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchFileType/MSFT_SPSearchFileType.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchIndexPartition/MSFT_SPSearchIndexPartition.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSecureStoreServiceApp/MSFT_SPSecureStoreServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppProxyGroup/MSFT_SPServiceAppProxyGroup.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuerProviderRealms/MSFT_SPTrustedIdentityTokenIssuerProviderRealms.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileServiceApp/MSFT_SPUserProfileServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncConnection/MSFT_SPUserProfileSyncConnection.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWeb/MSFT_SPWeb.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/MSFT_SPWebAppAuthentication.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/MSFT_SPWorkManagementServiceApp.psm1
- Modules/SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Tests/Unit/SharePointDsc/SharePointDSC.SPPowerPointAutomationServiceApp.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPInstallPrereqs.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchContentSource.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileProperty.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSection.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppAuthentication.Tests.ps1
- Tests/Unit/UnitTestHelper.psm1
Implemented strict mode when running all DSC resource unit tests.
A few changes was necessary in many or the resources to be able to successfully run with strict mode. Some of the resources had bugs that prevented them from working as intended in certain situations.
Implementation of strict mode version 2 is the goal, but it requires many more modifications in order to execute successfully.
- Partly implements #901 (only strict mode version 1)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/999)
> Implement Strict Mode Version 1

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkflowService/MSFT_SPWorkflowService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkflowService/MSFT_SPWorkflowService.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPWorkflowService/readme.md
- Modules/SharePointDsc/Examples/Resources/SPWorkflowService/2-RegisterWorkflowService.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWorkflowService.Tests.ps1
Added scope name for workflow service resource
Implemented support for detecting changes in WorkflowHostUri and ScopeName
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1005)
> SPWorkflowService: Added scope name for workflow service resource

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/MSFT_SPUserProfileProperty.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileProperty.Tests.ps1
User profile property mappings did not work due to incorrect parameter and variable usage.
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1011)
> SPUserProfileProperty: Fixed provisioning of user profile property mappings

- Modules/SharePointDsc/Examples/Small Farm/SharePoint.SSL.ps1
Added Central Admin on SSL example
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1025)
> Added Central Admin on SSL example

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
v3.2 prep
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1027)
> Preparations for v3.2 release

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuerProviderRealms/MSFT_SPTrustedIdentityTokenIssuerProviderRealms.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/MSFT_SPUserProfileProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/MSFT_SPWebAppAuthentication.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppClientCallableSettings/MSFT_SPWebAppClientCallableSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.psm1
Implemented (temporary) workaround for 'PSDSCUseIdenticalMandatoryParametersForDSC' issue introduced in PSSA v1.18.
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1041)
> Workaround for PSSA v1.18 issue

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPAppManagementServiceApp/MSFT_SPAppManagementServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSelfServiceSiteCreation/MSFT_SPSelfServiceSiteCreation.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSelfServiceSiteCreation/MSFT_SPSelfServiceSiteCreation.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSitePropertyBag/MSFT_SPSitePropertyBag.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSitePropertyBag/MSFT_SPSitePropertyBag.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSitePropertyBag/readme.md
- Modules/SharePointDsc/Examples/Resources/SPSelfServiceSiteCreation/4-EnableSelfServiceSiteCreationForSP2019.ps1
- Modules/SharePointDsc/Examples/Resources/SPSitePropertyBag/1-AddWebAppPropertyBag.ps1
- Modules/SharePointDsc/Examples/Resources/SPSitePropertyBag/2-RemoveWebAppPropertyBag.ps1
- Modules/SharePointDsc/Examples/Resources/readme.md
- Modules/SharePointDsc/Modules/SharePointDsc.WebApplication/SPWebApplication.Throttling.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPAppManagementServiceApp.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSelfServiceSiteCreation.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSitePropertyBag.Tests.ps1
This PR fixes several issues and introduced one new resource
- Fixes #885 
- Fixes #895 
- Fixes #1024 
- Fixes #1043 
- Fixes #1044 
- Fixes #1047 
And fixed issue with SPWebAppThrottlingSettings where ChangeLogRetentionDays was not updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1045)
> Rollup bugfix PR plus one new resource

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparation for v3.3 release
N/A
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1048)
> Prepare v3.3 release

- appveyor.yml
Update version number in appveyor.yml
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1051)
> Update version number in appveyor.yml

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparations for v3.4 release
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1063)
> v3.4 preparations

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/Readme.md
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
Throw error when CentralAdministrationUrl is HTTP. (Looking at documentation now to find a place to explain the CentralAdministrationUrl parameter. I'll push another commit shortly)
- Fixes #1065 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1066)
> SPFarm: Fixes #1065

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
Preparations for the release of v3.5
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1083)
> v3.5 release preparations

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1
SPTrustedRootAuthority: Fixes issue where Set method throws an error because the parameter CertificateFilePath is not read correctly.
None.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1089)
> SPTrustedRootAuthority: Fixes issue where Set method throws an error because the parameter CertificateFilePath is not read correctly

- CHANGELOG.md
- Modules/SharePointDsc/SharePointDsc.psd1
v3.6 Prep
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1101)
> v3.6 prep changes

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/MSFT_SPWebAppAuthentication.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPWebAppAuthentication.Tests.ps1
SPWebAppAuthentication: Fixes issue where Test method return false on NON-US OS.
- Fixes #1105 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1106)
> SPWebAppAuthentication: Fixes #1105

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarmSolution/MSFT_SPFarmSolution.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarmSolution.Tests.ps1
Fixes issue where SPFarmSolution can't deploy to a specific webapp
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1108)
> Fix fo WebApp scoped solutions

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/Readme.md
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
Add support for vanity hosts on HTTP to CA (issue #1102). Still testing this but wanted to go ahead and get the PR in to keep it on my radar (and get initial code review results).
- Fixes #1102 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1114)
> SPFarm: Add support for vanity hosts on HTTP to CA #1102

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
Add support for changing the authentication method of an already-created Central Administration web application from NTLM to Kerberos and vice versa.
- Fixes #1115 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1120)
> SPFarm: Add support for changing CA auth method

- .gitignore
- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/MSFT_SPDistributedCacheService.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/Readme.md
- Modules/SharePointDsc/Examples/Resources/SPDistributedCacheService/3-MultiServerCache.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPDistributedCacheService.Tests.ps1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1128)
> Improved Error Message + Restoration of missing text

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPServiceAppSecurity/MSFT_SPServiceAppSecurity.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuerProviderRealms/MSFT_SPTrustedIdentityTokenIssuerProviderRealms.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPUserProfileProperty/MSFT_SPUserProfileProperty.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/MSFT_SPWebAppAuthentication.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppClientCallableSettings/MSFT_SPWebAppClientCallableSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPWebAppPolicy/MSFT_SPWebAppPolicy.psm1
- Modules/SharePointDsc/SharePointDsc.psd1
Preparations for the v3.7 of Wednesday October 30th 2019
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/powershell/sharepointdsc/1129)
> v3.7 preparations

- CHANGELOG.md
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.psm1
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/MSFT_SPSearchContentSource.schema.mof
- Modules/SharePointDsc/DSCResources/MSFT_SPSearchContentSource/readme.md
- Modules/SharePointDsc/Examples/Resources/SPDistributedCacheService/3-MultiServerCache.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPSearchContentSource.Tests.ps1
* CrawlSetting Parameter previously not utilized/referenced (aside from throwing exceptions) within Set-TargetResource.  Recommend reviewing use of CrawlEverything and CrawlFirstOnly as valid values in CrawlSetting as part of a future Breaking Change build.
* Added CrawlVirtualServers and CrawlSites as valid values to CrawlSetting to align with [SharePointCrawlBehavior enumeration](https://docs.microsoft.com/en-us/powershell/module/sharepoint-server/new-spenterprisesearchcrawlcontentsource?view=sharepoint-ps)
* Continued to allow default value of CrawlEverything mapped to CrawlVirtualServers for non-breaking change, with verbose output advising of future major build deprecation of CrawlEverything from SharePoint Content Sources.
* Additional error message correction to reflect correct …
> #1124 Add CrawlSetting to SharePoint Content Sources

- CHANGELOG.md
- README.md
Correct issue with publishing preview module
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1151)
> Correct issue with publishing preview module

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedSecurityTokenIssuer/MSFT_SPTrustedSecurityTokenIssuer.psm1
If RegisteredIssuerNameRealm was specified it would not be applied in the configuration
None
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1148)
> SPTrustedSecurityTokenIssuer: Fixed RegisteredIssuerNameRealm not applied

- CHANGELOG.md
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerADResourcePoolSync.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerAdditionalSettings.tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerConnector.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerGlobalPermissions.tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerGroup.tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerTimeSheetSettings.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerUserSyncSettings.tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerWssSettings.tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.Util.Tests.ps1
Correct issue with Pester tests, that breaks multiple PRs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1166)
> Correct issue with Pester tests

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPAzureAccessControlServiceAppProxy/MSFT_SPAzureAccessControlServiceAppProxy.psm1
- SharePointDsc/DSCResources/MSFT_SPAzureAccessControlServiceAppProxy/MSFT_SPAzureAccessControlServiceAppProxy.schema.mof
- SharePointDsc/DSCResources/MSFT_SPAzureAccessControlServiceAppProxy/readme.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.schema.mof
- SharePointDsc/DSCResources/MSFT_SPFarm/Readme.md
- SharePointDsc/DSCResources/MSFT_SPOAppPrincipalMgmtServiceAppProxy/MSFT_SPOAppPrincipalMgmtServiceAppProxy.psm1
- SharePointDsc/DSCResources/MSFT_SPOAppPrincipalMgmtServiceAppProxy/MSFT_SPOAppPrincipalMgmtServiceAppProxy.schema.mof
- SharePointDsc/DSCResources/MSFT_SPOAppPrincipalMgmtServiceAppProxy/readme.md
- SharePointDsc/DSCResources/MSFT_SPTrustedSecurityTokenIssuer/MSFT_SPTrustedSecurityTokenIssuer.psm1
- SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.psm1
- SharePointDsc/DSCResources/MSFT_SPUserProfileSyncService/MSFT_SPUserProfileSyncService.schema.mof
- SharePointDsc/Examples/Resources/SPAzureAccessControlServiceAppProxy/1-CreateServiceApplicationProxy.ps1
- SharePointDsc/Examples/Resources/SPFarm/4-CreateBasicFarmWithApplicationCredentialKey.ps1
- SharePointDsc/Examples/Resources/SPOAppPrincipalMgmtServiceAppProxy/1-CreateServiceApplicationProxy.ps1
- SharePointDsc/Examples/Resources/SPUserProfileServiceApp/2-NoILMUsed.ps1
- SharePointDsc/Examples/Resources/SPUserProfileServiceApp/3-SiteNamingConflictResolution.ps1
- SharePointDsc/Examples/Resources/SPUserProfileSyncService/1-Example.ps1
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- Tests/Unit/SharePointDsc/SharePointDsc.SPAzureAccessControlServiceAppProxy.Tests.ps1
- Tests/Unit/SharePointDsc/SharePointDsc.SPOAppPrincipalMgmtServiceAppProxy.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPFarm.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPProjectServerConnector.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileProperty.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncConnection.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileSyncService.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.Util.Tests.ps1
SPUserProfileSyncService remove deprecated FarmAccount parameter
- Fixes #1165 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1170)
> SPUserProfileSyncService remove deprecated FarmAccount parameter

- CHANGELOG.md
- RequiredModules.psd1
- SharePointDsc/DSCResources/MSFT_SPPasswordChangeSettings/MSFT_SPPasswordChangeSettings.schema.mof
- SharePointDsc/DSCResources/MSFT_SPSearchIndexPartition/readme.md
- SharePointDsc/DSCResources/MSFT_SPSubscriptionSettingsServiceApp/MSFT_SPSubscriptionSettingsServiceApp.schema.mof
- SharePointDsc/DSCResources/MSFT_SPSubscriptionSettingsServiceApp/readme.md
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- build.ps1
- build.yaml
The PR implements various updates for the CD/CI pipeline
- Fixes #1173 
- Fixes #1160 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1175)
> Various updates for CD/CI pipeline

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSearchAuthoritativePage/MSFT_SPSearchAuthoritativePage.psm1
Fix Demoted Action of SPSearchAuthoritativePage
-Fixes #1167 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1186)
> SPSearchAuthoritativePage Fix 1167

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Mocks.cs
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchTopology.Tests.ps1
Fixes issue in SPSearchTopology where an exception was thrown if the FirstPartitionDirectory didn't exist on the local server, which is not required when the local server isn't going to run the Index Component.
- Fixes #1095 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1211)
> SPSearchTopology: Fixes issue where exception was incorrectly thrown

- CHANGELOG.md
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- azure-pipelines.yml
- build.yaml
This PR fixes the issue reported with the new event log functionality.
- Fixes #1214 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1215)
> Quick fix for v4.1

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.psm1
- SharePointDsc/DSCResources/MSFT_SPWebAppSuiteBar/MSFT_SPWebAppSuiteBar.schema.mof
- tests/Unit/SharePointDsc/SharePointDsc.SPWebAppSuiteBar.Tests.ps1
Unblocked configuration for SP2019. This resource works fine on SharePoint 2019 as long as it's not expected that it affects modern pages.
Verbose messages has been added to clarify this.
- Fixes #1139
- Reverts SP2019 blocking introduced in #1210
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1240)
> SPWebAppSuiteBar: Unblocked configuration for SP2019

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- SharePointDsc/Modules/SharePointDsc.Farm/SPFarm.psm1
This PR implements support for precreated databases.
Partly fixes issue #1241 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1242)
> [SPFarm] Implemented support for precreated databases (partly)

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPWorkflowService/MSFT_SPWorkflowService.psm1
An error was thrown when configuring workflow service when no workflow was already configured.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1253)
> SPWorkflowService: Fixed error when no workflow service is configured

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPInstall/Readme.md
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
This PR adds trusted domain support to the Test-SPDscIsADUser helper function and documents an issue with the SharePoint 2019 installer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1257)
> Added domain support to Test-SPDscIsADUser

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
This PR updates the diagnostic logging output to properly output credentials instead of the PSCredential object name.
- Fixes #1258 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1259)
> Corrected diagnostic logging of credentials

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPAlternateUrl/MSFT_SPAlternateUrl.psm1
If specified URL has a trailing slash and the AAM doesn't it is not recognized and Set throws an error
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1266)
> SPAlternateUrl: Fixes Issue with Trailing Slash

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1
- SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.schema.mof
- SharePointDsc/DSCResources/MSFT_SPDocIcon/readme.md
- SharePointDsc/Examples/Resources/SPDocIcon/1-ConfigureDocIcon.ps1
- SharePointDsc/Examples/Resources/SPDocIcon/2-RemoveDocIcon.ps1
- build.yaml
- tests/Unit/SharePointDsc/SharePointDsc.SPDocIcon.Tests.ps1
This PR adds a new resource called SPDocIcon, which is able to configure file types in the DocIcon XML file.
- Fixes #1276 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1282)
> [SPDocIcon] Added new resource

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPUsageDefinition/MSFT_SPUsageDefinition.psm1
- SharePointDsc/DSCResources/MSFT_SPUsageDefinition/MSFT_SPUsageDefinition.schema.mof
- SharePointDsc/DSCResources/MSFT_SPUsageDefinition/readme.md
- SharePointDsc/Examples/Resources/SPUsageDefinition/1-Configure.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPUsageDefinition.Tests.ps1
This PR adds a new resource for managing Usage data collection definitions
- Fixes #1304 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1305)
> [SPUsageDefinition] Added new resource

- CHANGELOG.md
- azure-pipelines.yml
- build.yaml
- codecov.yml
- SharePointDsc
- Fixed code coverage in pipeline.
None.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1308)
> SharePointDsc: Fix code coverage in pipeline

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.psm1
- SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/MSFT_SPSecurityTokenServiceConfig.schema.mof
- SharePointDsc/DSCResources/MSFT_SPSecurityTokenServiceConfig/readme.md
- SharePointDsc/DSCResources/MSFT_SPService/MSFT_SPService.psm1
- SharePointDsc/DSCResources/MSFT_SPService/MSFT_SPService.schema.mof
- SharePointDsc/DSCResources/MSFT_SPService/readme.md
- SharePointDsc/Examples/Resources/SPService/1-StartService.ps1
- SharePointDsc/Examples/Resources/SPService/2-StopService.ps1
- azure-pipelines.yml
- build.yaml
- codecov.yml
- tests/Unit/SharePointDsc/SharePointDsc.SPService.Tests.ps1
Adding new SPService resource to manage provisioning/deprovisioning MinRole services
- Fixes #1235 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1309)
> Added SPService resource

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
Fix issue where developer dashboard could not be configured on first farm setup.
N/A
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1316)
> Fix developer dashboard config on first farm setup

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPInstallLanguagePack/MSFT_SPInstallLanguagePack.psm1
Detection of norwegian language pack fixed by checking the culture info LCID, and not display name
- Fixes #1323 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1324)
> SPInstallLanguagePack: Fix detection of norwegian language pack

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.psm1
- SharePointDsc/DSCResources/MSFT_SPFarm/MSFT_SPFarm.schema.mof
- SharePointDsc/DSCResources/MSFT_SPFarm/Readme.md
Add parameter SkipRegisterAsDistributedCacheHost to SPFarm to allow to explicitely set it
- Related to https://github.com/dsccommunity/SharePointDsc/issues/1321
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1325)
> Add parameter SkipRegisterAsDistributedCacheHost to SPFarm

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPAppDomain/MSFT_SPAppDomain.psm1
- SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/Readme.md
- SharePointDsc/DSCResources/MSFT_SPWebAppHttpThrottlingMonitor/MSFT_SPWebAppHttpThrottlingMonitor.psm1
- SharePointDsc/DSCResources/MSFT_SPWebAppHttpThrottlingMonitor/MSFT_SPWebAppHttpThrottlingMonitor.schema.mof
- SharePointDsc/DSCResources/MSFT_SPWebAppHttpThrottlingMonitor/readme.md
- SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/MSFT_SPWorkManagementServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/readme.md
- SharePointDsc/Examples/Resources/SPWebAppHttpThrottlingMonitor/1-ConfigureMemoryCounter.ps1
- SharePointDsc/Examples/Resources/SPWebAppHttpThrottlingMonitor/1-Example.ps1
- SharePointDsc/Examples/Resources/SPWebAppHttpThrottlingMonitor/2-ConfigureProcessorCounter.ps1
- azure-pipelines.yml
- tests/Unit/SharePointDsc/SharePointDsc.SPWebAppHttpThrottlingMonitor.Tests.ps1
This PR adds a new resource to manage the HTTP Throttling Monitor settings.
It also changes the DevOps config to use the new Windows Server 2022 image, which should run much faster.
- Fixes #1329 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1341)
> New SPWebAppHttpThrottlingMonitor resource

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPAppDomain/MSFT_SPAppDomain.psm1
- SharePointDsc/DSCResources/MSFT_SPContentDatabase/MSFT_SPContentDatabase.psm1
- SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/MSFT_SPExcelServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPExcelServiceApp/Readme.md
- SharePointDsc/DSCResources/MSFT_SPManagedMetadataServiceApp/MSFT_SPManagedMetaDataServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchTopology/MSFT_SPSearchTopology.psm1
- SharePointDsc/DSCResources/MSFT_SPService/readme.md
- SharePointDsc/DSCResources/MSFT_SPWebAppAuthentication/MSFT_SPWebAppAuthentication.schema.mof
- SharePointDsc/DSCResources/MSFT_SPWebAppClientCallableSettings/MSFT_SPWebAppClientCallableSettings.schema.mof
- SharePointDsc/DSCResources/MSFT_SPWebAppHttpThrottlingMonitor/MSFT_SPWebAppHttpThrottlingMonitor.psm1
- SharePointDsc/DSCResources/MSFT_SPWebAppHttpThrottlingMonitor/MSFT_SPWebAppHttpThrottlingMonitor.schema.mof
- SharePointDsc/DSCResources/MSFT_SPWebAppHttpThrottlingMonitor/readme.md
- SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/MSFT_SPWorkManagementServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPWorkManagementServiceApp/readme.md
- SharePointDsc/Examples/Resources/SPWebAppHttpThrottlingMonitor/1-ConfigureMemoryCounter.ps1
- SharePointDsc/Examples/Resources/SPWebAppHttpThrottlingMonitor/2-ConfigureProcessorCounter.ps1
- SharePointDsc/Modules/SharePointDsc.Search/SPSearchServiceApp.psm1
- azure-pipelines.yml
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPWebAppHttpThrottlingMonitor.Tests.ps1
Fixed issue where search analytics database name was hardcoded.
Fixed issue if search database names contained one or more spaces.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1331)
> SPSearchServiceApp: Fixed issue with hardcoded database name and space

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPSite.Tests.ps1
This PR fixes issue 990, where the following error was thrown if a site collection was created immediately after the farm was created:
"**Invalid field name. {cbb92da4-fd46-4c7d-af6c-3128c2a5576e}**"
- Fixes #990 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1342)
> Fixed #990 and added logging to SPSearchServiceApp

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1
This PR fixes an issue with checking incorrect IdentifierClaim in SPTrustedIdentityTokenIssuer
- Fixes #1328 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1343)
> [SPTrustedIdentityTokenIssuer] Fixes issue with checking incorrect IdentifierClaim

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPDocIcon/MSFT_SPDocIcon.psm1
- SharePointDsc/DSCResources/MSFT_SPHealthAnalyzerRuleState/MSFT_SPHealthAnalyzerRuleState.schema.mof
- SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPServiceAppPool/MSFT_SPServiceAppPool.psm1
- SharePointDsc/DSCResources/MSFT_SPSite/MSFT_SPSite.psm1
- SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
- SharePointDsc/Modules/SharePointDsc.Reverse/SharePointDsc.Reverse.psm1
- SharePointDsc/Modules/SharePointDsc.Search/SPSearchServiceApp.psm1
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPDocIcon.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPServiceAppPool.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPSite.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPWebApplication.Tests.ps1
This Bugfix PR fixes several bugs / closes several issues
- Fixes #1346
- Fixes #1347
- Fixes #1348 
- Fixes #1349
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1350)
> Bugfix PR: #1346, #1347, #1348 and #1349

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
This PR also adds the check for SQL Auth to the Test method of the Search service app.
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1352)
> [SPSearchServiceApp] Added SQL Auth check to Test method

- CHANGELOG.md
- SharePointDsc/Modules/SharePointDsc.Reverse/SharePointDsc.Reverse.psm1
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1353)
> Updated ReverseDSC Sizing on the screen for responsiveness

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPLogLevel/MSFT_SPLogLevel.psm1
- SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
- SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.schema.mof
- SharePointDsc/Examples/Resources/SPWebApplication/2-Example.ps1
- SharePointDsc/Modules/SharePointDsc.Reverse/SharePointDsc.Reverse.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPLogLevel.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPWebApplication.Tests.ps1
Added option to configure SiteDataServers to the SPWebApplication resource
- Fixes #562 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1359)
> [SPWebApplication] Added option to configure SiteDataServers 

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPCertificate/MSFT_SPCertificate.psm1
- SharePointDsc/DSCResources/MSFT_SPCertificate/MSFT_SPCertificate.schema.mof
- SharePointDsc/DSCResources/MSFT_SPCertificate/readme.md
- SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
- SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.schema.mof
- SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.psm1
- SharePointDsc/DSCResources/MSFT_SPWebApplicationExtension/MSFT_SPWebApplicationExtension.schema.mof
- SharePointDsc/Examples/Resources/SPCertificate/1-ImportPFXCertificate.ps1
- SharePointDsc/Examples/Resources/SPCertificate/2-ImportCERCertificate.ps1
- SharePointDsc/Examples/Resources/SPCertificate/3-RemovePFXCertificate.ps1
- SharePointDsc/Examples/Resources/SPWebApplication/3-Example.ps1
- SharePointDsc/Examples/Resources/SPWebApplicationExtension/1-Example.ps1
- SharePointDsc/Examples/Resources/SPWebApplicationExtension/2-Example.ps1
- SharePointDsc/SharePointDsc.psd1
- tests/Unit/SharePointDsc/SharePointDsc.SPCertificate.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPWebApplication.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPWebApplicationExtension.Tests.ps1
This PR adds a new SPCertificate resource to import certificates to the new Certificate Management feature in SharePoint Subscription Edition and updates SPWebApplication/SPWebApplicationExtension to support the configuration of certificates.
- Fixes #1363 
- Fixes #1364 
- Fixes #1365 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1362)
> [SPCertificate/SPWebApplication/SPWebApplicationExtension] New and updated resources to support certificate management

- CHANGELOG.md
- azure-pipelines.yml
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1367)
> Updated pipeline yml

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/readme.md
- tests/Unit/SharePointDsc/SharePointDsc.SPTrustedIdentityTokenIssuer.Tests.ps1
Update resource SPTrustedIdentityTokenIssuer to support OIDC trust parameters, introduced with SharePoint Subscription
None
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1369)
> Update resource SPTrustedIdentityTokenIssuer to support OIDC

- .github/CODEOWNERS
- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedRootAuthority/MSFT_SPTrustedRootAuthority.psm1
- tests/RunUnitTestsForAllResources.ps1
- tests/RunUnitTestsForResource.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPTrustedRootAuthority.Tests.ps1
Fixing issue in SPTrustedRootAuthority and added some script to simplify running Pester tests.
- Fixes #1371 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1374)
> Fix issue in SPTrustedRootAuthority and simplified running Pester tests

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/Readme.md
Added a clarification that the ServerProvisionOrder only uses hostnames. Which hopefully saves someone else some time:)
None
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1382)
> [SharePointDistributedCacheService]: Documentation added

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPWebApplication/MSFT_SPWebApplication.psm1
Fixed an issue where the Set method tried to use the Parameter SecureSocketsLayer with Set-SPWebApplication on SharePoint Server older than Subscription Edition.
- Fixes #1394
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1395)
> SPWebApplication: Use of SecureSocketsLayer Parameter

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/Readme.md
- SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/Readme.md
- SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1
- SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof
- SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/readme.md
- SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/1-AddStringFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/2-AddBoolToFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/3-AddIntToFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/4-RemoveFarmPropertyBag.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
Fixes two issues and implements a few logging improvements
- Fixes #1340 
- Fixes #1398 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1402)
> Fixes two issues and implements a few logging improvements

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPDistributedCacheClientSettings/Readme.md
- SharePointDsc/DSCResources/MSFT_SPDistributedCacheService/Readme.md
- SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.psm1
- SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/MSFT_SPFarmPropertyBag.schema.mof
- SharePointDsc/DSCResources/MSFT_SPFarmPropertyBag/readme.md
- SharePointDsc/DSCResources/MSFT_SPInstall/MSFT_SPInstall.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
- SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.psm1
- SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/MSFT_SPWebAppPeoplePickerSettings.schema.mof
- SharePointDsc/DSCResources/MSFT_SPWebAppPeoplePickerSettings/readme.md
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/1-AddStringFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/2-AddBoolToFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/3-AddIntToFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPFarmPropertyBag/4-RemoveFarmPropertyBag.ps1
- SharePointDsc/Examples/Resources/SPWebAppPeoplePickerSettings/1-Example.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPFarmPropertyBag.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPInstall.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchServiceApp.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPWebAppPeoplePickerSettings.Tests.ps1
- SPWebAppPeoplePickerSettings
- Added the CustomFilter parameter to the resource
- Added the ShortDomainName parameter to the resource
- SPWebAppPeoplePickerSettings
- Fixed an issue where the Set method would not update a non mandatory parameter on an existing SPWebAppPPSearchDomain
- Expanded the unit tests for AccessAcount
- Fixes #1393
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1396)
> SPWebAppPeoplePickerSettings: Adds support for parameter CustomFilter and ShortDomainName

- CHANGELOG.md
- SharePointDsc/WikiSource/Understanding-Resources.md
Removed extra empty cell.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1405)
> Wiki Resource overview: Formatting issue with credssp column

- CHANGELOG.md
- RequiredModules.psd1
- SharePointDsc/DSCResources/MSFT_SPSearchCrawlDatabase/MSFT_SPSearchCrawlDatabase.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchCrawlDatabase/MSFT_SPSearchCrawlDatabase.schema.mof
- SharePointDsc/DSCResources/MSFT_SPSearchCrawlDatabase/readme.md
- SharePointDsc/DSCResources/MSFT_SPSearchIndexPartition/MSFT_SPSearchIndexPartition.psm1
- SharePointDsc/DSCResources/MSFT_SPSearchServiceApp/MSFT_SPSearchServiceApp.psm1
- SharePointDsc/DSCResources/MSFT_SPShellAdmins/MSFT_SPShellAdmins.psm1
- SharePointDsc/DSCResources/MSFT_SPShellAdmins/readme.md
- SharePointDsc/Examples/Resources/SPSearchCrawlDatabase/1-Example.ps1
- SharePointDsc/Examples/Resources/SPSearchCrawlDatabase/2-Example.ps1
- SharePointDsc/Modules/SharePointDsc.Reverse/SharePointDsc.Reverse.psm1
- SharePointDsc/Modules/SharePointDsc.ShellAdmin/SPShellAdmin.psm1
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchCrawlDatabase.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPShellAdmins.Tests.ps1
- tests/Unit/SharePointDsc/SharePointDsc.SPUserProfileProperty.Tests.ps1
This PR adds the SPSearchCrawlDatabase resource, adds extra troubleshooting information, implements export logic for SPShellAdmin, increases export requirement to ReverseDsc v2.0.0.11 and fixes several bugs.
- Fixes #493 
- Fixes #1404 
- Fixes #1389 
help.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/sharepointdsc/1406)
> New resource and various bug fixes

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPPublishServiceApplication/MSFT_SPPublishServiceApplication.psm1
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
This PR fixes two issues
- Fixes #1420 
- Fixes #1422 
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1423)
> Fixing two issues

- CHANGELOG.md
- SharePointDsc/Modules/SharePointDsc.Util/SharePointDsc.Util.psm1
Starting with SharePoint Subscription 21H1, running `Import-Module SharePointServer -Verbose:$false` causes an exception.  
This PR removes this import if it detects SharePoint Subscription as it is unnecessary (even in SharePoint Subscription RTM)
- Fixes [#123](https://github.com/dsccommunity/SharePointDsc/issues/1424)
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1425)
> Remove unnecessary Import-Module in SharePoint Subscription to fix error in 23H1

- CHANGELOG.md
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1426)
> Corrected changelog

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPSearchCrawlerImpactRule/MSFT_SPSearchCrawlerImpactRule.psm1
- tests/Unit/SharePointDsc/SharePointDsc.SPSearchCrawlerImpactRule.Tests.ps1
Fixed an issue where the `SPEnterpriseSearchSiteHitRule` Cmdlets Parameter `SearchService` was called withg an `Search Service Application` Object instead of a supported `SearchServicePipeBind` Value.
Changed the passed Value to the Displayname of the Search Service Application
- Fixes #1446
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1447)
> SPSearchCrawlerImpactRule: Set-TargetRessource uses SearchServiceApplicationPipeBind instead of SearchServicePipeBind

- CHANGELOG.md
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.psm1
- SharePointDsc/DSCResources/MSFT_SPTrustedIdentityTokenIssuer/MSFT_SPTrustedIdentityTokenIssuer.schema.mof
SPTrustedIdentityTokenIssuer: add parameters OidcScope and UseStateToRedirect
help.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dsccommunity/SharePointDsc/1456)
> SPTrustedIdentityTokenIssuer: add parameters OidcScope and UseStateToRedirect
